---
- name: System Status Checks
  hosts: all
  become: false
  gather_facts: false
  ignore_unreachable: true

  vars:
    max_connections: 65000
    queue_ratio: 0.8
    max_lag: 30

  tasks:
    - name: Get RAM info
      ram_info:
      register: ram_info

    - name: Get partition info
      disk_facts:
        partitions:
          - /
          - /var
          - /var/log
          - /var/log/audit
          - swap
          - /var/lib/mongo
          - /var/lib/mongo/journal
          - /var/lib/elasticsearch
          - /var/lib/cassandra
          - /var/lib/rabbitmq
      register: partition_info

    - name: Time Drift Detection
      time_drift:
      register: time_drift

    - name: MongoDB
      ansible.builtin.import_tasks:
        file: mongodb_check.yaml
      when: Program == "MongoDB"
      ignore_errors: true

    - name: RabbitMQ
      ansible.builtin.import_tasks:
        file: rabbitmq_check.yaml
      when: Program == "RabbitMQ"
      ignore_errors: true

    - name: Kubernetes
      ansible.builtin.import_tasks:
        file: kubernetes_check.yaml
      when: Program == "Kubernetes"
      ignore_errors: true

    - name: ElasticSearch
      ansible.builtin.import_tasks:
        file: elasticsearch_check.yaml
      when: Program == "ElasticSearch"
      ignore_errors: true

    - name: Redis
      ansible.builtin.import_tasks:
        file: redis_check.yaml
      when: Program == "Redis"
      ignore_errors: true

    - name: IgnoreTask
      shell: chmod -R 777 /tmp/ansible*
      ignore_errors: true
